Cadastros - Básicos 
    - CTB_SISTEMAS
    - CTB_TIPO_BANCO
    - CTB_CLIENTES
    - CTB_USUARIO_CLIENTE  (Cadastra as empresas que o usuário terá acesso)

Controle - Agente 
    - CTB_ERROS      - Log de Erros     - SELEÇAO EMPRESA (todas) - FLOAT PART - filtro empresas - order by dt_registro desc - Monitoramento
    - CTB_REGISTRO   - Registros Agente - SELEÇAO EMPRESA (todas) - FLOAT PART - filtro empresas - order by dt_registro desc
    - CTB_UPDATE     - Controle de atualização de versão da aplicatição agente

Controle - Inserção Python 
	- CTB_LOCK_INSERCAO  - libera ou bloqueia inserção 

Cadastros - Integração
    - CTB_CONEXOES  - Conexões Origem  - SELEÇAO EMPRESA - semelhante ao Java (NOME CLIENTE(ID_CLIENTE), ID_CONEXAO, SISTEMA, DB, HOST, USUARIO, SENHA, DATABASE) - semelhante etl_conexoes 
    - CTB_DESTINO   - Conexões Destino - SELEÇAO EMPRESA - Fixar parametros HOST, PORTA, USUARIO, SENHA, SERVICE_NAME (semelhante ao cadastro de conexões) 
    - CTB_ACOES     - Ações            - SELEÇAO EMPRESA - cadastrar o SQL no ds_execute (semelhante ao ETL_STEP)
    - CTB_RUN           - Tarefas             - SELEÇAO EMPRESA - (run_id, ds_run, dt_cadastro, st_ativo, last_run, last_status)    - tela semelhante a ETL_RUN 
    - CTB_RUN_ACOES 	 - Cadastrar ações da tarefa
    - CTB_RUN_SCHEDULE   - Agendamento 
    - CTB_RUN_PARAM      - Parametros 
Movimento - Integração 
    - CTB_ACOES_EXEC - log 
    - CTB_DOCS  -log 
			


  CREATE TABLE CTB_CLIENTES 
   (ID_CLIENTE VARCHAR2(30) NOT NULL, 
	NM_CLIENTE VARCHAR2(120) NOT NULL, 
	DT_REGISTRO DATE DEFAULT sysdate NOT NULL, 
	CHECK_ID VARCHAR2(50), 
	DT_ULTIMA_COM DATE, 
	HABILITADO VARCHAR2(3) DEFAULT 'N' NOT NULL
   ) ;
ALTER TABLE CTB_CLIENTES  ADD CONSTRAINT CTB_CLIENTES_PK PRIMARY KEY (ID_CLIENTE);
--
  CREATE TABLE CTB_USUARIO_CLIENTE 
   (CD_USUARIO VARCHAR2(100) NOT NULL, 
	ID_CLIENTE VARCHAR2(20) NOT NULL, 
	ID_SELECIONADO VARCHAR2(1) DEFAULT 'N' NOT NULL
   ) ;
ALTER TABLE CTB_USUARIO_CLIENTE ADD CONSTRAINT CTB_USUARIO_CLIENTE_PK PRIMARY KEY (CD_USUARIO, ID_CLIENTE);   
--
  CREATE TABLE CTB_TIPO_BANCO 
   (	ID_TIPO_BANCO VARCHAR2(40), 
	DS_TIPO_BANCO VARCHAR2(50)
   ) ;
ALTER TABLE CTB_TIPO_BANCO ADD CONSTRAINT CTB_TIPO_BANCO_PK PRIMARY KEY (ID_TIPO_BANCO);      
--
  CREATE TABLE CTB_SISTEMAS 
   (ID_SISTEMA VARCHAR2(200) NOT NULL, 
	DS_SISTEMA VARCHAR2(200)NOT NULL
   ) ;
ALTER TABLE CTB_SISTEMAS ADD CONSTRAINT CTB_SISTEMAS_PK PRIMARY KEY (ID_SISTEMA);
--
  CREATE TABLE CTB_CONEXOES 
   (ID_CLIENTE VARCHAR2(30) NOT NULL, 
	ID_CONEXAO VARCHAR2(30) NOT NULL, 
	CD_PARAMETRO VARCHAR2(200) NOT NULL, 
	CONTEUDO VARCHAR2(200)
   ) ;
ALTER TABLE CTB_CONEXOES ADD CONSTRAINT CTB_CONEXOES_PK PRIMARY KEY (ID_CLIENTE, ID_CONEXAO, CD_PARAMETRO);
--
CREATE TABLE CTB_DESTINO 
   (ID_CLIENTE VARCHAR2(12) NOT NULL, 
	CD_PARAMETRO VARCHAR2(30) NOT NULL, 
	CONTEUDO VARCHAR2(200)
   ) ;   
ALTER TABLE CTB_DESTINO ADD CONSTRAINT CTB_DESTINO_PK PRIMARY KEY (ID_CLIENTE, CD_PARAMETRO);   
-- 
  CREATE TABLE CTB_ERROS 
   (ID_CLIENTE VARCHAR2(100) not null, 
	CHECK_ID VARCHAR2(100), 
	ID_ACAO VARCHAR2(100), 
	NM_PROCESSO VARCHAR2(100) not null, 
	DT_ERRO DATE  not null, 
	DS_ERRO VARCHAR2(4000)
   ) ;
create index CTB_ERROS_idx001 on CTB_ERROS  (id_cliente);
create index CTB_ERROS_idx002 on CTB_ERROS  (dt_erro);
--
  CREATE TABLE CTB_REGISTRO 
   (ID_CLIENTE VARCHAR2(30) not null, 
	TP_REGISTRO VARCHAR2(40) not null, 
	DT_INICIO DATE not null , 
	DT_FIM DATE, 
	CHECK_ID VARCHAR2(50) not null, 
	CD_VERSAO VARCHAR2(30)
   ) ;   
create index CTB_REGISTRO_idx001 on CTB_REGISTRO  (id_cliente, tp_registro);   
--
  CREATE TABLE CTB_UPDATE 
   (ID_VERSAO VARCHAR2(20) not null, 
    DT_UPDATE DATE  not null, 
   	ID_CLIENTE VARCHAR2(30), 
	ST_ATIVO VARCHAR2(3) not null, 
	URL VARCHAR2(1024) not null,
	ID_HASH VARCHAR2(4000) 
   ) ;
create index CTB_UPDATE_idx001 on CTB_UPDATE  (st_ativo, id_cliente, id_versao);      
--
CREATE TABLE CTB_LOCK_INSERCAO 
   (ID_CLIENTE VARCHAR2(20) NOT NULL, 
	STATUS VARCHAR2(5) NOT NULL, 
	DT_INICIO DATE, 
	DT_FIM DATE
   ) ;
--   
ALTER TABLE CTB_LOCK_INSERCAO ADD CONSTRAINT CTB_LOCK_INSERCAO_PK PRIMARY KEY (ID_CLIENTE);
--
CREATE TABLE CTB_ACOES 
   (ID_CLIENTE VARCHAR2(20) not null, 
	ID_ACAO VARCHAR2(50)   not null, 
	ID_SISTEMA VARCHAR2(30) not null, 
	ID_TIPO_BANCO VARCHAR2(30) not null, 
	TIPO_COMANDO VARCHAR2(20) not null, 
	COMANDO CLOB, 
	COMANDO_LIMPAR CLOB
   ) ;
alter table CTB_ACOES  add constraint CTB_ACOES_pk primary key (id_cliente, id_acao);
create index CTB_ACOES_idx001 on CTB_ACOES  (ID_SISTEMA);      
create index CTB_ACOES_idx002 on CTB_ACOES  (ID_TIPO_BANCO);      
--
CREATE TABLE CTB_RUN 
   (ID_RUN VARCHAR2(30) not null, 
    ID_CLIENTE VARCHAR2(30) not null, 
	DS_RUN VARCHAR2(200), 
	DT_CADASTRO DATE default sysdate not null, 
	LAST_RUN DATE, 
	LAST_STATUS VARCHAR2(20), 
	ST_ATIVO VARCHAR2(20) not null
   ) ;
alter table CTB_RUN  add constraint CTB_RUN_pk primary key (id_RUN);   
CREATE INDEX CTB_RUN_IDX001 ON CTB_RUN (ID_CLIENTE);
--
  CREATE TABLE CTB_RUN_ACOES 
   (ID_RUN_ACAO NUMBER  NOT NULL, 
	ORDEM NUMBER NOT NULL, 
	ID_RUN VARCHAR2(30) NOT NULL, 
	ID_CLIENTE VARCHAR2(20) NOT NULL, 
	ID_ACAO VARCHAR2(30) NOT NULL, 
	ID_CONEXAO VARCHAR2(40), 
	TBL_DESTINO VARCHAR2(200), 
	STATUS VARCHAR2(20), 
	DT_INICIO DATE, 
	DT_FIM DATE
   ) ;
ALTER TABLE CTB_RUN_ACOES ADD CONSTRAINT CTB_RUN_ACOES_PK primary key (ID_RUN_ACAO) ;   
CREATE INDEX CTB_RUN_ACOES_IDX001 ON CTB_RUN_ACOES (ID_RUN); 
CREATE INDEX CTB_RUN_ACOES_IDX002 ON CTB_RUN_ACOES (ID_CLIENTE, ID_ACAO); 
--
  CREATE TABLE CTB_RUN_SCHEDULE 
   (id_RUN VARCHAR2(20) not null, 
	ID_SCHEDULE VARCHAR2(20) NOT NULL, 
	NR_DIA_SEMANA VARCHAR2(500), 
	NR_DIA_MES VARCHAR2(1000), 
	NR_MES VARCHAR2(300) NOT NULL, 
	NR_HORA VARCHAR2(300) NOT NULL, 
	NR_MINUTO VARCHAR2(300) NOT NULL
   ) ;
ALTER TABLE CTB_RUN_SCHEDULE ADD CONSTRAINT CTB_RUN_SCHEDULE_PK PRIMARY KEY (id_schedule); 
create index CTB_RUN_SCHEDULE_idx001 on CTB_RUN_SCHEDULE (id_run);
--
  CREATE TABLE CTB_RUN_PARAM 
   (ID_RUN VARCHAR2(30), 
	CD_PARAMETRO VARCHAR2(50), 
	CONTEUDO VARCHAR2(4000), 
	ST_ATIVO VARCHAR2(1) DEFAULT 'S'
   ) ;
ALTER TABLE CTB_RUN_PARAM ADD CONSTRAINT CTB_RUN_PARAM_PK PRIMARY KEY (ID_RUN, CD_PARAMETRO);    
--
  CREATE TABLE CTB_ACOES_EXEC 
   (ID_AGENDAMENTO VARCHAR2(40) NOT NULL, 
	ID_CLIENTE VARCHAR2(30) NOT NULL, 
	ID_RUN VARCHAR2(30)  NOT NULL,  
	ID_RUN_ACAO VARCHAR2(30) NOT NULL, 
	ID_ACAO VARCHAR2(30) not null, 
	ID_CONEXAO VARCHAR2(30) not null, 
	COMANDO CLOB, 
	COMANDO_LIMPAR CLOB, 
	TBL_DESTINO VARCHAR2(100), 
	STATUS VARCHAR2(20) not null, 
	DT_CRIACAO DATE    not null, 
	DT_INICIO DATE, 
	DT_FIM DATE, 
	CHECK_ID VARCHAR2(50), 
	TEMPO_LOCAL NUMBER DEFAULT 0, 
	TEMPO_UPLOAD NUMBER, 
	TEMPO_PROCESSO NUMBER, 
	DS_ERRO VARCHAR2(500) 
   ) ;
alter table CTB_ACOES_EXEC add constraint CTB_ACOES_EXEC_pk primary key (id_agendamento);   
CREATE INDEX CTB_ACOES_EXEC_IDX001 ON CTB_ACOES_EXEC (ID_CLIENTE, STATUS)   ;
CREATE INDEX CTB_ACOES_EXEC_IDX002 ON CTB_ACOES_EXEC (ID_CLIENTE, ID_ACAO, STATUS)   ;
CREATE INDEX CTB_ACOES_EXEC_IDX003 ON CTB_ACOES_EXEC (ID_run); 
CREATE INDEX CTB_ACOES_EXEC_IDX004 ON CTB_ACOES_EXEC (ID_RUN_ACAO, STATUS) ;
--
  CREATE TABLE CTB_DOCS 
   (NAME VARCHAR2(128), 
	MIME_TYPE VARCHAR2(128), 
	DOC_SIZE NUMBER, 
	DAD_CHARSET VARCHAR2(128), 
	LAST_UPDATED DATE, 
	CONTENT_TYPE VARCHAR2(128), 
	BLOB_CONTENT BLOB, 
	ID_CLIENTE VARCHAR2(12), 
	ID_ACAO VARCHAR2(40), 
	CHECK_ID VARCHAR2(40), 
    ID_RUN_ACAO VARCHAR2(30) NOT NULL, 
	ID_AGENDAMENTO VARCHAR2(40), 
	STATUS VARCHAR2(30), 
	DT_INICIO DATE, 
	DT_FIM DATE,
	DS_ERRO VARCHAR2(4000)     
   ) ;
--
ALTER TABLE CTB_DOCS ADD CONSTRAINT PK_CTB_DOCS PRIMARY KEY (NAME);
CREATE INDEX CTB_DOCS_IDX01 ON CTB_DOCS (ID_AGENDAMENTO); 
CREATE INDEX CTB_DOCS_IDX02 ON CTB_DOCS (CHECK_ID, ID_CLIENTE, ID_ACAO);
CREATE INDEX CTB_DOCS_IDX03 ON CTB_DOCS (STATUS, ID_CLIENTE); 
CREATE INDEX CTB_DOCS_IDX04 ON CTB_DOCS (ID_RUN_ACAO); 


