create or replace FUNCTION check_id (PRM_CHAVE VARCHAR2) RETURN VARCHAR2 AS
     
    TYPE TP_ARRAY IS TABLE OF VARCHAR2(2000) INDEX BY BINARY_INTEGER;
    WS_ARRAY TP_ARRAY;
    WS_COUNTER INTEGER;

    WS_INDICE VARCHAR2(1);
    WS_INDICE_FAKE VARCHAR2(1);
    WS_SESSION VARCHAR2(2);
    WS_CHECK_IMEI VARCHAR2(3);
    WS_IMEI VARCHAR2(30) := '012756003461913877'; 

    WS_RETORNO VARCHAR2(30);

BEGIN

    WS_ARRAY(0) := 'QPWOLASJIE';
    WS_ARRAY(1) := 'ESLWPQMZNB';
    WS_ARRAY(2) := 'YTRUIELQCB';
    WS_ARRAY(3) := 'RADIOSULTE';
    WS_ARRAY(4) := 'RITALQWCVM';
    WS_ARRAY(5) := 'ZMAKQOCJDE';
    WS_ARRAY(6) := 'YTHEDJKSPQ';
    WS_ARRAY(7) := 'PIRALEZOUT';
    WS_ARRAY(8) := 'HJWPAXOQTI';
    WS_ARRAY(9) := 'DFRTEOAPQX';

    WS_INDICE      := (INSTR(WS_ARRAY(1),SUBSTR(PRM_CHAVE,6,1)))-1;
    WS_INDICE_FAKE := (INSTR(WS_ARRAY(2),SUBSTR(PRM_CHAVE,7,1)))-1;

    WS_SESSION    := (INSTR(WS_ARRAY(WS_INDICE), SUBSTR(PRM_CHAVE,4,1))-1) || 
                     (INSTR(WS_ARRAY(WS_INDICE), SUBSTR(PRM_CHAVE,5,1))-1);

    WS_CHECK_IMEI := (INSTR(WS_ARRAY(WS_INDICE_FAKE),SUBSTR(PRM_CHAVE,1,1))-1) ||
                     (INSTR(WS_ARRAY(WS_INDICE_FAKE),SUBSTR(PRM_CHAVE,2,1))-1) ||
                     (INSTR(WS_ARRAY(WS_INDICE_FAKE),SUBSTR(PRM_CHAVE,3,1))-1);

    WS_INDICE      := SUBSTR(TO_CHAR(SYSDATE,'SS'),2,1);
    WS_INDICE_FAKE := ABS((TO_NUMBER(WS_INDICE)-TO_NUMBER(SUBSTR(TO_CHAR(SYSDATE,'SS'),1,1))));
    WS_SESSION     := SUBSTR(WS_ARRAY(ABS(ABS(WS_INDICE - WS_INDICE_FAKE))),(TO_NUMBER(SUBSTR(WS_SESSION,1,1))+1),1) ||
                      SUBSTR(WS_ARRAY(ABS(ABS(WS_INDICE - WS_INDICE_FAKE))),(TO_NUMBER(SUBSTR(WS_SESSION,2,1))+1),1);

    WS_IMEI := SUBSTR(WS_ARRAY(WS_INDICE_FAKE),(TO_NUMBER(SUBSTR(WS_IMEI,12, 1))+1),1)||
               SUBSTR(WS_ARRAY(WS_INDICE_FAKE),(TO_NUMBER(SUBSTR(WS_IMEI,13, 1))+1),1)||
               SUBSTR(WS_ARRAY(WS_INDICE_FAKE),(TO_NUMBER(SUBSTR(WS_IMEI,14, 1))+1),1);

    WS_INDICE_FAKE := SUBSTR(WS_ARRAY(4),(TO_NUMBER(SUBSTR(WS_INDICE_FAKE, 1,1)+1)),1);
    WS_INDICE      := SUBSTR(WS_ARRAY(5),(TO_NUMBER(SUBSTR(WS_INDICE, 1,1)+1)),1);

    IF WS_CHECK_IMEI <> SUBSTR(WS_IMEI,9,3) THEN
        WS_RETORNO := 'ERRO';
    ELSE
        WS_RETORNO := WS_IMEI||WS_SESSION||WS_INDICE||WS_INDICE_FAKE;
    END IF;

    RETURN(WS_RETORNO);

END CHECK_ID;